name: Automated Code Review

on:
  workflow_call:
    inputs:
      ignore_glob:
        description: "Glob pattern to ignore files"
        required: false
        default: "['**/mocks/**', 'swagdocs/**']"
        type: string

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI.API_BASE: ${{vars.OPENAI_API_BASE}}
          OPENAI.KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB.BASE_URL: https://github.com/api/v3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: true
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: true
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: true
          GITHUB_ACTION_CONFIG.PR_ACTIONS: "[ 'opened', 'reopened', 'synchronize', 'ready_for_review']"
          CONFIG.MODEL: deepseek/deepseek-r1-0528-qwen3-8b
          CONFIG.FALLBACK_MODEL: deepseek/deepseek-r1-0528-qwen3-8b
          CONFIG.RESPONSE_LANGUAGE: ko-KR
          CONFIG.MAX_MODEL_TOKENS: 200000
          PR_REVIEWER.ENABLE_HELP_TEXT: true
          PR_REVIEWER.FINAL_UPDATE_MESSAGE: false
          PR_DESCRIPTION.MAX_AI_CALLS: 10
          PR_CODE_SUGGESTIONS.PUBLISH_OUTPUT_NO_SUGGESTIONS: false
          IGNORE.GLOB: ${{ inputs.ignore_glob }}
